### PR TITLE
Add Login and fix register

### LINKED ISSUE #14: Add login

### PR DESCRIPTION
**Pull request by AnastasiaPromtep**
Closes #14

### CODE REVIEW

**Comment by AnastasiaPromtep** [comment]
PR name has been change accordingly

**Comment by AnastasiaPromtep** [comment]
Though the git diff is showing many changes, there is only two files that will be merged.
I tried locally.

File: components/Login/index.js [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+  }
+}
+`;
+
+const Login = () => {
+  const [username, setUsername] = useState('');
+  const [password, setPassword] = useState('');
+  const [login, {
+    called: loginCalled,
+    loading: loginLoading,
```
[the remark this answers is not in the document]
Comment (AnastasiaPromtep) [reply components/Login/index.js]: Indeed they have been removed

File: components/Header/index.js [hunk 2]
```diff
@@ -1,18 +1,40 @@
...
+      return (
+        <Link href="/">
+          <a className={styles.link} title='Logout' onClick={onLogoutHandle}>Logout</a>
+        </Link>
+      );
+    } else {
+      return (
+        <Link href="/register">
+          <a className={styles.link} title='Register'>Register</a>
+        </Link>
```
Comment (maximelouet) [inline components/Header/index.js:22]: We could add a login link as well

File: pages/index.js [hunk 3]
```diff
@@ -1,8 +1,16 @@
...
-export default function Index() {
-  return (
-      <div>
-          <p>Touiteur</p>
+ const Index = () => {
+   const { getToken } = useContext(AuthenticationContext);
+
+   return (
+     <div>
+        { getToken() ? <p>logged in</p> : <Login /> }
```
Comment (maximelouet) [inline pages/index.js:10]: Maybe we could create a `isAuthenticated` boolean in `AuthenticationContext` to clarify this kind of checks? This would just be a one-liner but may improve code clarity. Tell me what you think

File: components/Header/index.js (hunk 2 above)
Comment (AnastasiaPromtep) [reply components/Header/index.js]: It has been added.

File: pages/index.js (hunk 3 above)
Comment (AnastasiaPromtep) [reply pages/index.js]: Good thinking. I added an isAuthenticated method

File: contexts/Authentication.js [hunk 4]
```diff
@@ -10,11 +10,13 @@ const AuthenticationContextProvider = (props) => {
   };
 
   const getToken = () => token;
+  const isAuthenticated = () => token !== '';
 
   return (
     <AuthenticationContext.Provider value={{
       storeToken: storeToken,
       getToken: getToken,
+      isAuthenticated: isAuthenticated
```
Comment (maximelouet) [inline contexts/Authentication.js:19]: Maybe it would be easier if `isAuthenticated` was a variable rather than a function? What do you think?

File: components/Header/index.js [hunk 5]
```diff
@@ -1,18 +1,45 @@
...
+  };
+
+  return (
+    <div>
+      <Link href="/">
+        <a className={styles.link} title='Home page'>Home</a>
+      </Link>
+      { authenticationLinks() }
+      <Link href="/about">
+        <a className={styles.link} title='About page'>About</a>
```
Comment (maximelouet) [inline components/Header/index.js:39]: I don't think you need `title` here as link texts are self-explanatory.

Comment (AnastasiaPromtep) [reply components/Header/index.js]: Useless indeed, I removed them.

File: contexts/Authentication.js (hunk 4 above)
Comment (AnastasiaPromtep) [reply contexts/Authentication.js]: It sounds better indeed.
